config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing_page#index'

  get  'sign_up',  to: 'registration#new',   as: :sign_up
  post 'sign_up',  to: 'registration#create'
  get  'sign_in',  to: 'session#new',        as: :sign_in
  post 'sign_in',  to: 'session#create'
  get  'sign_out', to: 'session#destroy',    as: :sign_out

  resources :orders, only: %i[index show create destroy]
  resources :payments, only: :create
  resources :products do
    resources :reviews, only: %i[index create destroy]
  end
  resource  :user, only: %i[show update]

  post 'contact', to: 'static_pages#contact', as: :contact

  # This has to stay the last line in the file to not interfere with other
  # routes. This way, we can avoid the "static_pages" part of the route and turn
  # "/static_pages/about" into "/about"
  get ':static_page_id', to: 'static_pages#index', as: :static_page
end

app/models/product.rb
class Product < ApplicationRecord
  include Reviewable

  has_many :orders

  validates :name, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  scope :name_like, ->(name) { where('name ilike ?', "%#{name}%") }

  def price_in_cents
    (price * 100).floor
  end

  def to_s
    name
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate!, except: %i[index show]
  before_action :set_product, only: %i[show edit update destroy]
  before_action :update_view_count, only: :show

  def index
    authorize Product, :show?
    @search_term = params[:search_term]
    @products = if @search_term
                  Product.name_like(@search_term)
                else
                  Product.all
                end
  end

  def show
    authorize product, :show?

    @review = Review.new(review_params)
    @view_count = view_count

    push_reviews_to_gon
  end

  def new
    @product = Product.new
    authorize product, :new?
  end

  def edit
    authorize product, :edit?
  end

  def create
    @product = Product.new(permitted_params)
    authorize @product, :create?

    if product.save
      flash[:success] = 'Product was created.'
      redirect_to product_path(product)
    else
      flash.now[:error] = 'The product could not be created. Please check your inputs.'
      render :new
    end
  end

  def update
    product.assign_attributes(permitted_params)
    authorize product, :update?

    if product.save
      flash[:success] = 'Product was updated.'
      redirect_to product_path(product)
    else
      flash.now[:error] = 'The product could not be updated. Please check your inputs.'
      render :edit
    end
  end

  def destroy
    authorize product, :destroy?
    product.destroy!
    flash[:success] = "Product '#{product.name}' deleted."
    redirect_to products_path
  end

  private

  attr_reader :product

  def permitted_params
    params.require(:product).permit(:name, :description, :image_url, :colour, :price)
  end

  def review_params
    return {} unless params[:review]

    params.require(:review).permit(:comment)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def view_count
    redis.hget(:product_view_count, product.id) || 0
  end

  def update_view_count
    redis.hincrby(:product_view_count, product.id, 1)
  end

  # TODO: Dry up (identical with ReviewsController)
  def push_reviews_to_gon
    gon.reviewable_id = product.id
    gon.average_rating = product.average_rating
    gon.reviews = serialized_teaser_reviews
  end

  def serialized_teaser_reviews
    ReviewSerializer.serialize(product.teaser_reviews, is_collection: true)
  end
end

app/views/products/_card.html.haml
- present(product) do |product|
  .product__card
    = link_to image_tag(product.image_url, class: 'img-responsive'), product
    .product__card-caption
      = product.name
    .product__card-price
      = product.formatted_price

app/views/products/_carousel.html.haml
#product-carousel.carousel.slide(data-ride='carousel')
  %ol.carousel-indicators
    - @products.each_with_index do |_, index|
      %li(data-target='#carousel' data-slide-to=index class="#{index.zero? ? 'active' : ''}")

  .carousel-inner(role='listbox')
    - @products.each_with_index do |product, index|
      - present(product) do |product|
        .item(class="#{index.zero? ? 'active' : ''}")
          = link_to image_tag(product.image_url), product_path(product)
          .carousel-caption
            %h3= product.name
            = product.formatted_price

  %a.left.carousel-control(href='#product-carousel' role='button' data-slide='prev')
    %span.glyphicon.glyphicon-chevron-left
  %a.right.carousel-control(href='#product-carousel' role='button' data-slide='next')
    %span.glyphicon.glyphicon-chevron-right

app/views/products/_form.html.haml
= form_for @product do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: :name
    = f.errors :name

  .form-group
    = f.label :description
    = f.text_area :description, rows: 10, class: 'form-control'

  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control'
    = f.errors :price

  .form-group
    = f.label :colour
    = f.text_field :colour, class: 'form-control'

  .form-group
    = f.label :image_url
    = f.text_field :image_url, class: 'form-control'

  = f.submit class: 'btn btn-primary'

app/views/products/edit.html.haml
.container
  %h1 Edit a product
  = render 'form'

app/views/products/index.html.haml
.container-fluid
  .products__container
    %h1 Browse all our products
    .row
      - @products.each do |product|
        .col-xs-12.col-sm-6.col-lg-4
          = render partial: 'products/card', locals: { product: product }

  - if authorize Product, :new?
    = link_to 'New Product', new_product_path, class: 'btn btn-primary'

app/views/products/new.html.haml
.container
  %h1 Create a new product
  = render 'form'

app/views/products/show.html.haml
- present(@product) do |product|
  #product(data-product-id="#{product.id}")
    .container
      %h1
        = product.name
        - if product.reviews.any?
          #average-rating.reviews__rating{ data: { score: product.average_rating } }
      .row
        .col-xs-12.col-md-4
          = image_tag(product.image_url, id: 'product-image', class: 'img-responsive', alt: '')
          %p.product__price-tag
            = product.formatted_price
          %p
            %strong Colour
            %br
            = product.colour
            %p
              This product has been viewed
              = @view_count
              times
          %p
            = link_to 'Back', products_path, class: 'btn btn-default'
            - if authorize @product, :edit?
              = link_to 'Edit', edit_product_path(product), class: 'btn btn-default'
            - if authorize @product, :destroy?
              = link_to 'Delete', product_path(product), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' }
        .col-xs-12.col-md-8
          .product_checkout
            - if signed_in?
              = form_with url: payments_url do |f|
                = f.hidden_field :product_id, value: product.id
                = render 'shared/stripe_checkout_button', product: product, user: current_user
            - else
              = link_to 'Pay with Card', sign_in_path, class: 'btn btn-primary'
          .product__description
            = product.description

            %hr
            %h3 What our customers say
            #product-reviews
              // Frontend rendering here