config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing_page#index'

  get  'sign_up',  to: 'registration#new',   as: :sign_up
  post 'sign_up',  to: 'registration#create'
  get  'sign_in',  to: 'session#new',        as: :sign_in
  post 'sign_in',  to: 'session#create'
  get  'sign_out', to: 'session#destroy',    as: :sign_out

  resources :orders, only: %i[index show create destroy]
  resources :payments, only: :create
  resources :products do
    resources :reviews, only: %i[index create destroy]
  end
  resource  :user, only: %i[show update]

  post 'contact', to: 'static_pages#contact', as: :contact

  # This has to stay the last line in the file to not interfere with other
  # routes. This way, we can avoid the "static_pages" part of the route and turn
  # "/static_pages/about" into "/about"
  get ':static_page_id', to: 'static_pages#index', as: :static_page
end

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed(data-toggle='collapse' data-target='#navbar' aria-expanded='false')
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .page-title.navbar-brand Bike Berlin

    #navbar.collapse.navbar-collapse
      %form.navbar-form.navbar-right(action=products_path)
        .form-group
          %input.form-control(type='text' name='search_term' placeholder='Product' value=@search_term)
        %button.btn.btn-default(type='submit') Search

      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'Home', root_path
        %li= link_to 'Products', products_path
        %li= link_to 'About', static_page_path(:about)
        %li= link_to 'Contact', static_page_path(:contact)
        - if signed_in?
          %li= link_to 'Logout', sign_out_path
          %li= link_to 'My Profile', user_path
        - else
          %li= link_to 'Login', sign_in_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CareerFoundryApp
    %meta(name='viewport' content='width=device-width, initial-scale=1')
    = csrf_meta_tags
    = action_cable_meta_tag

    = stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Montserrat'
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag    'application'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'
  %body
    = render 'layouts/navigation'
    = include_gon

    .container
      = render 'shared/flash_messages'
    = yield

    %footer.container-fluid
      &copy; Gerrit 2017